# Generated by Django 2.0.2 on 2019-08-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='FILENAME',
            field=models.ImageField(default='defualt.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='title',
            field=models.CharField(default='作品标题', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='description',
            field=models.CharField(default='在这里写作品的简介', max_length=100),
        ),
    ]
