# Generated by Django 2.0.2 on 2019-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0002_auto_20190816_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallary',
            name='FILENAME',
        ),
        migrations.AddField(
            model_name='gallary',
            name='image',
            field=models.ImageField(default='defualt.png', upload_to='images/'),
        ),
    ]
